// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/person.proto

package personpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersistenceService_GetPerson_FullMethodName   = "/person.PersistenceService/GetPerson"
	PersistenceService_ListPersons_FullMethodName = "/person.PersistenceService/ListPersons"
	PersistenceService_PostPerson_FullMethodName  = "/person.PersistenceService/PostPerson"
)

// PersistenceServiceClient is the client API for PersistenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersistenceServiceClient interface {
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
	ListPersons(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPersonResponse], error)
	PostPerson(ctx context.Context, in *PostPersonRequest, opts ...grpc.CallOption) (*PostPersonResponse, error)
}

type persistenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceServiceClient(cc grpc.ClientConnInterface) PersistenceServiceClient {
	return &persistenceServiceClient{cc}
}

func (c *persistenceServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, PersistenceService_GetPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) ListPersons(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPersonResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PersistenceService_ServiceDesc.Streams[0], PersistenceService_ListPersons_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GetPersonResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersistenceService_ListPersonsClient = grpc.ServerStreamingClient[GetPersonResponse]

func (c *persistenceServiceClient) PostPerson(ctx context.Context, in *PostPersonRequest, opts ...grpc.CallOption) (*PostPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostPersonResponse)
	err := c.cc.Invoke(ctx, PersistenceService_PostPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServiceServer is the server API for PersistenceService service.
// All implementations must embed UnimplementedPersistenceServiceServer
// for forward compatibility.
type PersistenceServiceServer interface {
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	ListPersons(*emptypb.Empty, grpc.ServerStreamingServer[GetPersonResponse]) error
	PostPerson(context.Context, *PostPersonRequest) (*PostPersonResponse, error)
	mustEmbedUnimplementedPersistenceServiceServer()
}

// UnimplementedPersistenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersistenceServiceServer struct{}

func (UnimplementedPersistenceServiceServer) GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedPersistenceServiceServer) ListPersons(*emptypb.Empty, grpc.ServerStreamingServer[GetPersonResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListPersons not implemented")
}
func (UnimplementedPersistenceServiceServer) PostPerson(context.Context, *PostPersonRequest) (*PostPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPerson not implemented")
}
func (UnimplementedPersistenceServiceServer) mustEmbedUnimplementedPersistenceServiceServer() {}
func (UnimplementedPersistenceServiceServer) testEmbeddedByValue()                            {}

// UnsafePersistenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServiceServer will
// result in compilation errors.
type UnsafePersistenceServiceServer interface {
	mustEmbedUnimplementedPersistenceServiceServer()
}

func RegisterPersistenceServiceServer(s grpc.ServiceRegistrar, srv PersistenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPersistenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersistenceService_ServiceDesc, srv)
}

func _PersistenceService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_ListPersons_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PersistenceServiceServer).ListPersons(m, &grpc.GenericServerStream[emptypb.Empty, GetPersonResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersistenceService_ListPersonsServer = grpc.ServerStreamingServer[GetPersonResponse]

func _PersistenceService_PostPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).PostPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_PostPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).PostPerson(ctx, req.(*PostPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersistenceService_ServiceDesc is the grpc.ServiceDesc for PersistenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "person.PersistenceService",
	HandlerType: (*PersistenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _PersistenceService_GetPerson_Handler,
		},
		{
			MethodName: "PostPerson",
			Handler:    _PersistenceService_PostPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPersons",
			Handler:       _PersistenceService_ListPersons_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/person.proto",
}
